### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#108] opened 2016-11-07 13:33 UTC
I get the error message
```
CMake Error at common/cmake/FindOpenCL.cmake:127 (find_package_handle_standard_args):
  Unknown CMake command "find_package_handle_standard_args".
Call Stack (most recent call first):
  CMakeLists.txt:65 (find_package)
```
I noticed that travis fails for commit 8a6d34ac24dad1f635d7a98d44b2bc3af8b21e28 because it doesn't have cmake 3.1, which makes sense. On the other hand, the newer commits have never been triggered and I don't know why. Could it be that the function in the error message requires cmake>=3 and the requirement was set back to 2.8?

**Comment by matze** [comment] 2016-11-07 13:43
Travis does not trigger because I disabled it for now, exactly because of that. However, `find_package_handle_standard_args` should work even with CMake 2.6.

**Comment by tfarago** [comment] 2016-11-07 14:18
From what I tested so far, it doesn't work on cmake 2.8.7 and 2.8.6. Could you check on ufo1 please? There we have cmake 2.8.6 which gives this error.

**Comment by matze** [comment] 2016-11-07 15:18
I think you haven't pasted the entire error log. I get this on compute1 (don't have access to the ANKA network):
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenCL (missing: OpenCL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  common/cmake/FindOpenCL.cmake:127 (find_package_handle_standard_args)
  CMakeLists.txt:65 (find_package)
```

This and similar errors like `libOpenCL.so` not found can be fixed by passing the correct libraries and paths to the configure step or afterwards with `ccmake`. The "problem" is that I now included the official CMake module to find OpenCL which in the long run is easier than maintaining our own but apparently is expecting somewhat sane installations.

**Comment by matze** [comment] 2016-11-07 15:37
Hmm, Travis agrees with your observation. I will test this weird stuff in a separate branch if I find the time.

**Closed** 2016-11-07 22:41 UTC
Labels: bug, high-prio

**Comment by matze** [comment] 2016-11-08 07:10
P.S.: Let me know if it works for you now. The problem is neither CMake 3 or non-existent HandleStandardArgs but the stupid way that module tries declare OpenCL found which definitely works on more recent distributions …

**Comment by tfarago** [comment] 2016-11-11 13:58
Hm, now it cannot find OpenCL on ufo1.

**Comment by matze** [comment] 2016-11-11 14:40
That's because OpenCL is very likely not installed in a standard place. In that case, you should add the include dir and library by hand with `ccmake`. In the past it worked because we added all kinds of paths to search for …

**Comment by tfarago** [comment] 2016-11-16 08:42
Yep, now it builds, thanks.
